import wx

class PollGui(wx.Dialog):
	def __init__(self):
		wx.Dialog.__init__(self, None, title="Compose poll", size=(350,200))
		self.panel = wx.Panel(self)
		self.main_box = wx.BoxSizer(wx.VERTICAL)
		self.runfor_label = wx.StaticText(self.panel, -1, "Run Poll &for (Days)")
		self.runfor = wx.SpinCtrl(self.panel, -1, min=1,max=7)
		self.main_box.Add(self.runfor, 0, wx.ALL, 10)
		self.runfor.SetFocus()
		self.opt1_label = wx.StaticText(self.panel, -1, "Option &1")
		self.opt1 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP)
		self.main_box.Add(self.opt1, 0, wx.ALL, 10)
		self.opt2_label = wx.StaticText(self.panel, -1, "Option &2")
		self.opt2 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP)
		self.main_box.Add(self.opt2, 0, wx.ALL, 10)
		self.opt3_label = wx.StaticText(self.panel, -1, "Option &3")
		self.opt3 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP)
		self.main_box.Add(self.opt3, 0, wx.ALL, 10)
		self.opt4_label = wx.StaticText(self.panel, -1, "Option &4")
		self.opt4 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP)
		self.main_box.Add(self.opt4, 0, wx.ALL, 10)
		self.ok = wx.Button(self.panel, wx.ID_OK, "&OK")
		self.ok.SetDefault()
		self.main_box.Add(self.ok, 0, wx.ALL, 10)
		self.close = wx.Button(self.panel, wx.ID_CANCEL, "&Cancel")
		self.main_box.Add(self.close, 0, wx.ALL, 10)
		self.panel.Layout()
